# =============================================================================
# FW_SERVER - chrony : serveur NTP pour le LAN_SERVER
# =============================================================================

# Source amont : FW_ISP
server 192.168.99.1 iburst
server 0.pool.ntp.org iburst
server 1.pool.ntp.org iburst

# Servir le LAN_SERVER
allow 192.168.20.0/24
allow 192.168.10.0/24

local stratum 10

driftfile /var/lib/chrony/drift
logdir    /var/log/chrony

makestep 1.0 3
rtcsync