# =============================================================================
# FW_SERVER - Configuration IPsec strongSwan
# =============================================================================

config setup
    charondebug="ike 2, knl 2, cfg 2"
    uniqueids=yes

conn site-to-site
    keyexchange=ikev2
    ike=aes256-sha256-modp2048!
    ikelifetime=8h

    esp=aes256-sha256-modp2048!
    lifetime=1h
    pfs=yes

    # Côté SERVER : on inverse left/right
    left=10.20.0.2
    leftsubnet=192.168.20.0/24
    leftid=@fw-server.labcyber.local

    right=10.10.0.2
    rightsubnet=192.168.10.0/24
    rightid=@fw-client.labcyber.local

    authby=secret
    auto=add                            # Côté serveur, on accepte les connexions
    dpdaction=restart
    dpddelay=30s
    dpdtimeout=120s
    closeaction=restart