global(workDirectory="/var/spool/rsyslog")

module(load="imtcp")
input(type="imtcp" port="514")

module(load="imudp")
input(type="imudp" port="514")

template(name="RemotePerHostPerProgram" type="string" string="/var/log/remote/%HOSTNAME%/%PROGRAMNAME%.log")

*.* action(
    type="omfile"
    DynaFile="RemotePerHostPerProgram"
    DirCreateMode="0755"
    FileCreateMode="0644"
)