# =============================================================================
# FW_CLIENT - dnsmasq : DHCP serveur pour LAN_CLIENT
# Équivalent : FortiGate > Network > Interfaces > DHCP server
# =============================================================================

# Désactive DNS (FW_ISP fait DNS), on ne fait que DHCP ici
port=0

# DHCP sur l'interface LAN
interface=__LAN_IF__
bind-interfaces

# Plage DHCP (équivalent FortiGate Address Range)
# Note : 192.168.10.10-50 sont réservés pour les conteneurs statiques (client1, client2, kali)
dhcp-range=192.168.10.100,192.168.10.200,12h

# Options DHCP fournies aux clients
dhcp-option=3,192.168.10.1            # Default Gateway
dhcp-option=6,192.168.99.1            # DNS Server (FW_ISP via mgmt)
dhcp-option=42,192.168.99.1           # NTP Server
dhcp-option=15,labcyber.local         # Domaine

# Logs
log-dhcp
log-facility=/var/log/fw/dhcp.log