# =============================================================================
# FW_CLIENT - Configuration IPsec strongSwan
# =============================================================================

config setup
    charondebug="ike 2, knl 2, cfg 2"
    uniqueids=yes

conn site-to-site
    keyexchange=ikev2
    ike=aes256-sha256-modp2048!
    ikelifetime=8h

    esp=aes256-sha256-modp2048!
    lifetime=1h

    left=__LOCAL_WAN_IP__
    leftsubnet=192.168.10.0/24,192.168.30.0/24
    leftid=@fw-client.labcyber.local

    right=__REMOTE_WAN_IP__
    rightsubnet=192.168.20.0/24,192.168.50.0/24
    rightid=@fw-server.labcyber.local

    authby=secret
    auto=start
    dpdaction=restart
    dpddelay=30s
    dpdtimeout=120s
    closeaction=restart