# =============================================================================
# FW_ISP - Configuration chrony (serveur NTP)
# Équivalent : pfSense > Services > NTP
# =============================================================================

# Sources NTP en amont (pool publics)
server 0.pool.ntp.org iburst
server 1.pool.ntp.org iburst
server 2.pool.ntp.org iburst
server time.google.com iburst

# Permettre aux clients des LANs de se synchroniser
allow 10.10.0.0/24
allow 10.20.0.0/24
allow 192.168.10.0/24
allow 192.168.20.0/24
allow 192.168.99.0/24

# Servir l'heure même sans synchro Internet (utile en lab)
local stratum 10

# Fichiers
driftfile /var/lib/chrony/drift
logdir    /var/log/chrony

# Synchro système rapide au démarrage
makestep 1.0 3
rtcsync