# =============================================================================
# FW_ISP - Configuration dnsmasq (DNS Resolver + DHCP)
# =============================================================================

port=53
domain-needed
bogus-priv
no-resolv
no-poll

server=8.8.8.8
server=1.1.1.1
server=9.9.9.9

cache-size=1000
neg-ttl=60

domain=labcyber.local
local=/labcyber.local/

address=/fw-isp.labcyber.local/__VIP_MGMT_IP__
address=/fw-client.labcyber.local/__CLIENT_MGMT_VIP__
address=/fw-server.labcyber.local/__SERVER_MGMT_VIP__
address=/web.labcyber.local/192.168.20.10
address=/ssh.labcyber.local/192.168.20.11
address=/voip1.labcyber.local/192.168.30.10
address=/guest1.labcyber.local/192.168.40.10
address=/dmz-web.labcyber.local/192.168.50.10

log-queries
log-facility=/var/log/fw/dnsmasq.log

interface=__WAN_CLIENT_IF__
interface=__WAN_SERVER_IF__
interface=__MGMT_IF__
except-interface=__INTERNET_IF__
bind-dynamic